-- shoes.sql
CREATE TABLE IF NOT EXISTS shoes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shoe_id INTEGER NOT NULL,
    review_text TEXT NOT NULL,
    rating INTEGER DEFAULT 0,
    FOREIGN KEY(shoe_id) REFERENCES shoes(id)
);
